---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "order-producer"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-producer
    version: v1
    app.kubernetes.io/part-of: demo-kafka
    app.openshift.io/runtime: quarkus
  name: order-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-producer
      version: v1
  template:
    metadata:
      labels:
        app: order-producer
        version: v1
        app.kubernetes.io/part-of: demo-kafka
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms100m -Xmx100m -Xmn100m
        name: order-producer
        image: quay.io/froberge/order-producer:1.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        resources:
          requests: 
            memory: "100Mi" 
            cpu: "200m" # 1/5 core
          limits:
            memory: "200Mi"
            cpu: "500m" 
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/live
          initialDelaySeconds: 5
          periodSeconds: 4
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/ready
          initialDelaySeconds: 6
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
      serviceAccount: "order-producer"